services:
  # The final destination
  target-server:
    container_name: z76-target-server.com
    image: z76-target-server
    build:
      dockerfile: deployments/server.Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - minitor-net

  # The intermediate proxy node
  proxy-node:
    container_name: z76-proxy-node.local
    image: z76-proxy-node
    build:
      dockerfile: deployments/node.Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./certs:/app/certs
    networks:
      - minitor-net

  # The user/client application
  demo-client:
    container_name: z76-demo-client
    image: z76-demo-client
    build:
      dockerfile: deployments/demo.Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./certs:/app/certs
    depends_on:
      - proxy-node
    networks:
      - minitor-net

networks:
  minitor-net:
    name: z76_network
    external: true
